---
title: "Jackson Mouse Study"
author: "Philip LoGerfo"
date: "May 2021"
output: html_document

---

#############

```{r get dependencies}
  
  library(png)

```


#############

```{r read in csv and png files}

# Read in the CSV and PNG Files

 pngPaths <- dir(path ="~/Test_set_Lg/Test_Set_Lg", pattern = "*.png", full.names = TRUE, recursive = TRUE)
 pngNames <- dir(path ="~/Test_set_Lg/Test_Set_Lg", pattern = "*.png", full.names = FALSE, recursive = TRUE)

 
  #########################
 
 csvPaths <- dir(path ="~/Test_set_Lg/Test_Set_Lg", pattern = "*.csv", full.names = TRUE, recursive = TRUE)
 csvNames <- dir(path ="~/Test_set_Lg/Test_Set_Lg", pattern = "*.csv", full.names = FALSE, recursive = TRUE)




```

#################


```{r warning = FALSE }

##Convert pixel counts to area (mm^2) and then convert void area to volumes

# Below are a bunch of variables that are initialized before the operation

base <- NULL  
pnames <- NULL
totala <- NULL
micv <- NULL
primv <- NULL
totalv <- NULL
primavg = NULL
microavg = NULL
tavg <- NULL
stdmm <- NULL

for (i in 1:length(csvPaths)) {
  
  # Read in the PNG file that corresponds with the CSV file
  pp <- readPNG(pngPaths[i])
  # estimate the pixel area of the cage floor
  tempbase <- length(which(pp > .05))
  base <- c(base, tempbase)
  
  # Read in the CSV file 
  pf <- read.delim(csvPaths[i], sep = ",", header = TRUE, row.names = 1)
  
  # make sure there are pee events
  if (dim(pf[1]) > 0) {
    
    #convert pixels to area
    stdmm <- tempbase/(265*111)
    
    #calculate volume 
    pvol <- (pf[1]/stdmm)*0.283
    
    # make a list of unfiltered total voids
    #tpf <- pf[1]
    # filter out very small area sizes
    #filter <- which(pf[,1] > 1500)
    
    # filter out very small volumes
    filter <- which(pvol > 2)
    
    # make a list of voids for file i
    fpf <- pvol[filter,1]
    
    # check again for pee events after filtering
    if (length(fpf) > 0) {
      
      # count the number of total voids
      tempEvent <- length(fpf)
      #add the total void count from that file to list totalv
      totalv <- c(totalv, tempEvent)
      
      # count microvoids
      tempmic <- which(fpf < 22)
      if (length(tempmic > 0)) {
        # add the total micro void count to list microv
        micv <- c(micv, length(tempmic))
        # makes a list of micro voids only
        mfpf <- fpf[tempmic]
        # calculate the mean of micro voids
        tempmic <- mean(mfpf)
        # add the mean of micro voids to list microavg
        microavg <- c(microavg, tempmic)
      }
      else {
        # if there are no micro voids
        micv <- c(micv, 0)
        microavg = c(microavg, 0)
      }
      
      # count primaryvoids
      tempprim <- which(fpf >= 22)
      if (length(tempprim > 0)) {
        # add the total primary void count to list primv
        primv <- c(primv, length(tempprim))
        # makes a list of primary voids only
        pfpf <- fpf[tempprim]
        # calculate the mean of primary voids
        tempprimavg <- mean(pfpf)
        # add the mean of primary voids to list primavg
        primavg <- c(primavg, tempprimavg)
        
      }
      else {
        # if there are no primary voids
        primv <- c(primv, 0)
        primavg = c(primavg, 0)
      }
      
      # sum the total area of all pee events   
      tempa <- sum(fpf)
      totala <- c(totala, tempa)
      
      # calculate the mean of all voids
      tempavg <- mean(fpf)
      tavg <- c(tavg, tempavg)
    }
    
    else {
      # If there are no micro or primary voids, but some voids < 1500 in area
      #   totala <- c(totala, sum(tpf))
      #  totalv <- c(totalv,  length(tpf))
      micv <- c(micv, 0)
      primv <- c(primv, 0)
      #    tavg <- c(tavg, mean(tpf))
      primavg = c(primavg, 0)
      microavg = c(microavg, 0)
      
      totala <- c(totala, 0)
      totalv <- c(totalv,  0)
      tavg <- c(tavg, 0)
      
    }
    
  }
  else {
    
    totala <- c(totala, 0)
    totalv <- c(totalv, 0)
    micv <- c(micv, 0)
    primv <- c(primv, 0)
    tavg <- c(tavg, 0)
    primavg = c(primavg, 0)
    microavg = c(microavg, 0)
    
  } 
  
  
  # Add the name of data file to list pnames   
  tempName <- csvNames[i]
  pnames <- c(pnames, tempName)
}
```
###################

Look at the nameOfFile variable. That is the name of the file that will be written with all the results in it.
You can change it to anything you want. Make sure to put the name in quotes "".


```{r }

# Format the results into a table and write to csv file 

# Make sure you know the name of the file that is written!
nameOfFile <- "pVolsData.csv"

pdata <- data.frame(row.names = pnames, csvNames = pnames, Total_Volumes = totala, Total_Voids = totalv, Total_Mean = tavg,
                    Primary_Voids = primv, Primary_Mean = primavg, 
                    Micro_Voids = micv, Micro_Mean = microavg) 


write.table(pdata, nameOfFile, sep = ",", row.names = FALSE)




```

